import React, { useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { MetricCard } from '../components/MetricCard';
import { Card } from '../components/Card';
import { Badge } from '../components/Badge';
import { ProgressBar } from '../components/ProgressBar';
import { useAgentContext } from '../context/AgentDataContext';

export function ZKProofs() {
  const { proofs } = useAgentContext();

  const [filter, setFilter] = useState<'All' | 'PASS' | 'FAIL'>('All');
  const [search, setSearch] = useState('');

  const totalProofs  = proofs.length;
  const passed       = proofs.filter(p => p.status === 'PASS').length;
  const failed       = proofs.filter(p => p.status === 'FAIL').length;
  const passRate     = totalProofs > 0 ? Math.round((passed / totalProofs) * 100) : 0;

  const displayed = proofs.slice(0, 50).filter(p => {
    if (filter !== 'All' && p.status !== filter) return false;
    if (search && !p.hash.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const pillStyle = (active: boolean): React.CSSProperties => ({
    padding: '5px 14px',
    borderRadius: 20,
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: 500,
    fontSize: 12,
    cursor: 'pointer',
    border: active ? '0.5px solid var(--brand-200)' : '0.5px solid var(--border-primary)',
    background: active ? 'var(--brand-100)' : 'var(--bg-secondary)',
    color: active ? 'var(--brand-700)' : 'var(--text-secondary)',
    transition: 'all 0.15s ease',
  });

  return (
    <div className="page-fade" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div>
        <h1 style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 600, fontSize: 20, color: 'var(--text-primary)', marginBottom: 4 }}>
          ZK Proof Monitor
        </h1>
        <p style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 400, fontSize: 13, color: 'var(--text-tertiary)', marginBottom: 20 }}>
          All proofs generated by Risc0 guest · validated against strategy rules
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 10 }}>
        <MetricCard label="Total proofs" value={String(totalProofs)} />
        <MetricCard label="Passed" value={<span style={{ color: 'var(--green-text)' }}>{passed}</span>} />
        <MetricCard label="Failed" value={<span style={{ color: 'var(--red-text)' }}>{failed}</span>} />
        <MetricCard label="Pass rate" value={<span style={{ color: 'var(--brand-700)' }}>{passRate}%</span>} />
      </div>

      <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 16 }}>
        {(['All', 'PASS', 'FAIL'] as const).map(f => (
          <button key={f} style={pillStyle(filter === f)} onClick={() => setFilter(f)}>{f}</button>
        ))}
        <input
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search hash…"
          style={{
            marginLeft: 'auto',
            width: 200, height: 32,
            padding: '0 10px',
            border: '0.5px solid var(--border-primary)',
            borderRadius: 'var(--radius-md)',
            background: 'var(--bg-secondary)',
            fontFamily: "'DM Sans', sans-serif",
            fontWeight: 400,
            fontSize: 12,
            color: 'var(--text-primary)',
            outline: 'none',
          }}
          onFocus={e => (e.target.style.borderColor = 'var(--brand-600)')}
          onBlur={e => (e.target.style.borderColor = 'var(--border-primary)')}
        />
      </div>

      <div style={{ border: '0.5px solid var(--border-primary)', borderRadius: 'var(--radius-lg)', overflow: 'hidden', background: 'var(--bg-primary)' }}>
        {displayed.length === 0 ? (
          <div style={{ padding: 32, textAlign: 'center', color: 'var(--text-tertiary)', fontFamily: "'DM Sans', sans-serif", fontSize: 13 }}>
            {proofs.length === 0 ? 'No proofs yet — start the agent to generate ZK proofs' : 'No proofs match the current filter'}
          </div>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: 'var(--bg-secondary)', height: 38, borderBottom: '0.5px solid var(--border-primary)' }}>
                {['Status', 'Proof Hash', 'Decision', 'Rule', 'Timestamp', 'On-chain'].map(col => (
                  <th key={col} style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: 12, color: 'var(--text-tertiary)', padding: '0 14px', textAlign: 'left' }}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {displayed.map((proof, i) => {
                const isFail = proof.status === 'FAIL';
                return (
                  <tr
                    key={proof.id}
                    style={{
                      height: 48,
                      borderBottom: i < displayed.length - 1 ? '0.5px solid var(--border-secondary)' : 'none',
                      borderLeft: isFail ? '2px solid var(--red-mid)' : undefined,
                      transition: 'background 0.15s',
                      cursor: 'default',
                    }}
                    onMouseEnter={e => (e.currentTarget.style.background = 'var(--bg-secondary)')}
                    onMouseLeave={e => (e.currentTarget.style.background = '')}
                  >
                    <td style={{ padding: '0 14px' }}>
                      <Badge variant={proof.status === 'PASS' ? 'green' : 'red'}>{proof.status}</Badge>
                    </td>
                    <td style={{ padding: '0 14px', fontFamily: "'DM Mono', monospace", fontWeight: 400, fontSize: 12, color: 'var(--text-secondary)' }}>
                      {proof.hash.slice(0, 7)}…{proof.hash.slice(-4)}
                    </td>
                    <td style={{ padding: '0 14px' }}>
                      <Badge variant={proof.decision === 'BUY' ? 'green' : proof.decision === 'SELL' ? 'red' : 'amber'}>{proof.decision}</Badge>
                    </td>
                    <td style={{ padding: '0 14px', fontFamily: "'DM Sans', sans-serif", fontWeight: 400, fontSize: 12, color: 'var(--text-secondary)' }}>{proof.rule}</td>
                    <td style={{ padding: '0 14px', fontFamily: "'DM Mono', monospace", fontWeight: 400, fontSize: 11, color: 'var(--text-tertiary)', whiteSpace: 'nowrap' }}>
                      {new Date(proof.timestamp).toISOString().slice(0, 19).replace('T', ' ')}
                    </td>
                    <td style={{ padding: '0 14px' }}>
                      <a
                        href={`https://sepolia.etherscan.io/search?q=${proof.hash}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ display: 'flex', alignItems: 'center', gap: 4, color: 'var(--blue-text)', textDecoration: 'none' }}
                      >
                        <ExternalLink size={12} />
                        <span style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 400, fontSize: 12 }}>Etherscan</span>
                      </a>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>

      <Card style={{ marginTop: 0 }}>
        <div style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: 13, color: 'var(--text-primary)', marginBottom: 12 }}>Rule validation breakdown</div>
        {[
          { rule: 'Max position size ≤ 25%', pass: `${passed}/${totalProofs}`, pct: passRate },
          { rule: 'Max drawdown ≤ 10%',      pass: `${totalProofs}/${totalProofs}`, pct: 100 },
          { rule: 'Single asset ≤ 50%',      pass: `${totalProofs}/${totalProofs}`, pct: 100 },
        ].map(({ rule, pass, pct }, i, arr) => (
          <div key={rule} style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '10px 0',
            borderBottom: i < arr.length - 1 ? '0.5px solid var(--border-secondary)' : 'none',
            gap: 16,
          }}>
            <span style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 400, fontSize: 12, color: 'var(--text-secondary)' }}>{rule}</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
              <Badge variant="green">{pass}</Badge>
              <div style={{ width: 80 }}>
                <ProgressBar value={pct} color="var(--green-mid)" height={4} />
              </div>
            </div>
          </div>
        ))}
      </Card>
    </div>
  );
}
